server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_route #路由id，没有固定规则但要求唯一，建议配合服务名
          #http方式
          #uri: http://localhost:8001 #匹配后提供服务的路由地址
          #注册中心服务方式
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/getPerson/** #断言，路径相匹配的进行路由
          #filters:
            #- AddRequestParameter=X-Request-Id,1024 #过滤器工厂会在匹配的请求头加上一对请求头，名称为X-Request-Id值为1024

        - id: payment_route2 #路由id，没有固定规则但要求唯一，建议配合服务名
          #http方式
          #uri: http://localhost:8001 #匹配后提供服务的路由地址
          #注册中心服务方式
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb  #断言，路径相匹配的进行路由
            - After=2022-10-10T11:18:53.852317500+08:00[Asia/Shanghai]
            #- Before=2022-10-10T11:18:53.852317500+08:00[Asia/Shanghai]
            #- Between=2022-10-10T11:18:53.852317500+08:00[Asia/Shanghai],2022-10-10T11:18:53.852317500+08:00[Asia/Shanghai]
            #- Cookie=username,mzq
            #- Header=X-Request-Id,\d+ #请求头要有X-Request-Id属性并且值为整数的正则表达式
            #- Host=**.jmu.com
            #- Method=GET
            #- Query=username,\d+  要有用户名username且值要是整数才能路由

eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      #defaultZone: http://eureka7001.com:7001/eureka
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka #集群版