server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1 #采样率在0到1之间，1表示全部采集

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydatabase?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  ###consul 服务注册中心
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        #host :127.0.0.1
        service-name: ${spring.application.name}

eureka:
  client:
    #将自己注册到eurekServer  默认是true
    register-with-eureka: true
    #是否从eurekaServer抓取已有的注册信息，默认true，单节点无所谓，集群必须设置true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka #集群版
  instance:
    instance-id: payment8001
    prefer-ip-address: true   #访问路径可以显示IP地址
    #eureka客户端向服务端发送心跳的时间间隔 单位为秒 默认30s
    lease-renewal-interval-in-seconds: 1
    #eureka服务端在收到最后一次心跳后等待时间上线，单位为秒 默认90s  超时会剔除服务
    lease-expiration-duration-in-seconds: 2

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: pers.jmu.springcloud.entities
